password_generator:
    passwordLength: 12 #значение длины пароля
    numbers: true #использовать числа или нет
    upperCase: true  #использовать латинские символы верхнего регистра или нет
    lowerCase: true #использовать латинские символы нижнего регистра или нет
    specialChars: true #использовать спецсимволы или нет
